name: Deploy to Tencent
on:
  push:
    tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
      - 'v*'
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    environment: prod
    # 步骤
    steps:
    - name: Deploy
      # 支持拷贝和SSH，因为服务器在中国。因此使用SSH + GIT
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.USER_HOST }}
        user: ${{ secrets.USER_NAME }}
        pass: ${{ secrets.USER_PASS }}
        port: 22
        connect_timeout: 10s
        first_ssh: |
          cd Blog
          git pull
          rm -rf .next
          rm -rf .contentlayer
          rm -rf package-lock.json
          rm -rf public/sitemap-0.xml
          npm i
          npm run build
        last_ssh: |
          pm2 restart wissbell 
