name: Build app and deploy to Tencent
on:
  push:
    branches:
      - main
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    environment: prod
    # 步骤
    steps:
    - name: Checkout Code
    # 使用别人的action
      uses: actions/checkout@v2
    # 步骤名称
    - name: use node
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16 # node版本
    
 
    - name: npm install
      # 步骤执行指令
      run: npm install
    #working-directory此命令的运行目录
      working-directory: ./
 
    - name: build
    #执行build命令，根据个人情况修改，如有多种配置可以改成build:prod,build:dev
      run: npm run build
      env:
        UPSTASH_REDIS_REST_URL: ${{ vars.UPSTASH_REDIS_REST_URL }}
        UPSTASH_REDIS_REST_TOKEN: ${{ vars.UPSTASH_REDIS_REST_TOKEN }}
        NEXT_PUBLIC_BEAM_TOKEN: ${{ vars.NEXT_PUBLIC_BEAM_TOKEN }}
      working-directory: ./
      
    # 命名这个任务为发布Deploy
    - name: Deploy
      # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.USER_HOST }}
        user: ${{ secrets.USER_NAME }}
        pass: ${{ secrets.USER_PASS }}
        port: 22
        connect_timeout: 10s
        scp: |
          './*' => /root/wissbell/
        last_ssh: |
          pm2 restart wissbell 
